apiVersion: v1
kind: ConfigMap
metadata:
  name: web-health-check
data:
  config.yml: |
    port: 8080
    tz: Europe/Kiev
    timeout: 5
    # default scheduler
    cron: "*/30 * 9-21 * * *"

    notificationMethods:
      slack:
        type: slack
        webhook: https://hooks.slack.com/services/XXX/XXX/XXX
      email:
        type: email
        email: alert@example.com

    notifications: 
      - slack

    failureThreshold: 6
    failureInterval: 12

    dataDir: ./data
    # in seconds
    notificationInterval: 900

    checks:
      - name: Prometheus Dev
        url: http://prometheus.dev.company.com/graph
        cron: "*/30 */1 9-21 * * 1-5"
      - name: company.com
        url: https://company.com/home/
        cron: "*/30 */1 9-21 * * 1-5"
      - name: company2.com
        url: https://company2.com/home/
      - name: Gitlab
        url: https://gitlab.company.com/-/liveness?token=XXX
        contentType: application/json
        response: '{"status":"ok"}'
      - name: Prometheus Prod
        url: http://prometheus.prod.company.com/graph
      - name: app1
        url: https://app1.company2.com/health_check
        response: '{"mongodb":"UP","amqp":"UP","status":"UP"}'
      - name: app2
        url: https://app2.prod.company.com/health_check
        response: '{"status":"UP"}'
